### ISSUE TITLE
공원 정보 조회 api

### ISSUE THREAD

**Issue by melitina915** [solux-gobajago/28th_1_Gabojago_HangangFlow_Back#5]
## ✅ Checklist
- [x] 완료된 항목은 체크해주세요
- [x] 이슈 제목 작성

## ✏ Description
- 공원 정보 조회 api 구현

## 📋 TODO
- [x] userUuid binary(16)으로
- [x] 데이터베이스 park로 연결
